import pandas as pd
import numpy as np
import regex as re

def preprocessing(data):
  df=data.drop(['STUDYID','VISIT','MISC_TARC_PAT_VISIT','CCR','CCR_YES','CCR_CL_IMPRESS_CODE','CCR_MCIAMEM','CCR_MCIAPLUS','CCR_MCIAPLAN','CCR_MCIAPATT','CCR_MCIAPEX',
               'CCR_MCIAPVIS','CCR_MCINON1','CCR_MCIN1LAN','CCR_MCIN1ATT','CCR_MCIN1EX','CCR_MCIN1VIS','CCR_MCINON2','CCR_MCIN2LAN','CCR_MCIN2ATT','CCR_MCIN2EX','CCR_MCIN2VIS',
               'CCR_YES_NOTES','MISC_SITEID','A1_BIRTHYR','A1_EVENTDATEX','A1_HANDEDNESS','A1_HISPANIC','A1_HISPANIC_TYPE','A1_HISPORX','A1_MARISTAT','A1_RACE','A1_RACESEC',
               'A1_RESIDENC','A41_PMA','A41_PMAF','A41_PMAFU','A41_PMAP','A41_PMAPF','A41_PMAPFU','A41_PMAPREV','A41_PMART','A41_PMAS','A41_PMASTDA','A41_PMASTMO','A41_PMASTYR',
               'A41_PMASU','A41_PMB','A41_PMBF','A41_PMBFU','A41_PMBP','A41_PMBPF','A41_PMBPFU','A41_PMBPREV','A41_PMBRT','A41_PMBS','A41_PMBSTDA','A41_PMBSTMO','A41_PMBSTYR',
               'A41_PMBSU','A42_VEA','A42_VEAF','A42_VEAFU','A42_VEAPREV','A42_VEART','A42_VEAS','A42_VEASU','A43_ADA','A43_ADACONT','A43_ADAENDDA','A43_ADAENDMO','A43_ADAENDYR',
               'A43_ADAF','A43_ADAFU','A43_ADAPREV','A43_ADART','A43_ADAS','A43_ADASTDA','A43_ADASTMO','A43_ADASTYR','A43_ADASU','A43_ADB','A43_ADBCONT','A43_ADBENDDA','A43_ADBENDMO',
               'A43_ADBENDYR','A43_ADBF','A43_ADBFU','A43_ADBPREV','A43_ADBRT','A43_ADBS','A43_ADBSTDA','A43_ADBSTMO','A43_ADBSTYR','A43_ADBSU','A43_ADC','A43_ADCCONT','A43_ADCENDDA',
               'A43_ADCENDMO','A43_ADCENDYR','A43_ADCF','A43_ADCFU','A43_ADCPREV','A43_ADCRT','A43_ADCS','A43_ADCSTDA','A43_ADCSTMO','A43_ADCSTYR','A43_ADCSU','A43_ADD','A43_ADDCONT',
               'A43_ADDENDDA','A43_ADDENDMO','A43_ADDENDYR','A43_ADDF','A43_ADDFU','A43_ADDPREV','A43_ADDRT','A43_ADDS','A43_ADDSTDA','A43_ADDSTMO','A43_ADDSTYR','A43_ADDSU','A43_ADE','A43_ADECONT',
               'A43_ADEENDDA','A43_ADEENDMO','A43_ADEENDYR','A43_ADEF','A43_ADEFU','A43_ADEPREV','A43_ADERT','A43_ADES','A43_ADESTDA','A43_ADESTMO','A43_ADESTYR','A43_ADESU','A43_ADF',
               'A43_ADFCONT','A43_ADFENDDA','A43_ADFENDMO','A43_ADFENDYR','A43_ADFF','A43_ADFFU','A43_ADFPREV','A43_ADFRT','A43_ADFS','A43_ADFSTDA','A43_ADFSTMO','A43_ADFSTYR','A43_ADFSU',
               'A43_ADMEDEVER','A44_DRG_TRIAL','A44_DRG_TRIALX','A44_SSA','A44_SSAF','A44_SSAFU','A44_SSAPREV','A44_SSART','A44_SSAS','A44_SSASTDA','A44_SSASTMO','A44_SSASTYR','A44_SSASU',
               'A44_SSB','A44_SSBF','A44_SSBFU','A44_SSBPREV','A44_SSBRT','A44_SSBS','A44_SSBSTDA','A44_SSBSTMO','A44_SSBSTYR','A44_SSBSU','A44_SSC','A44_SSCF','A44_SSCFU',
               'A44_SSCPREV','A44_SSCRT','A44_SSCS','A44_SSCSTDA','A44_SSCSTMO','A44_SSCSTYR','A44_SSCSU','A44_SSD','A44_SSDF','A44_SSDFU','A44_SSDPREV','A44_SSDRT',
               'A44_SSDS','A44_SSDSTDA','A44_SSDSTMO','A44_SSDSTYR','A44_SSDSU','A44_SSE','A44_SSEF','A44_SSEFU','A44_SSEPREV','A44_SSERT','A44_SSES','A44_SSESTDA','A44_SSESTMO',
               'A44_SSESTYR','A44_SSESU','A44_SSF','A44_SSFF','A44_SSFFU','A44_SSFPREV','A44_SSFRT','A44_SSFS','A44_SSFSTDA','A44_SSFSTMO','A44_SSFSTYR','A44_SSFSU',
               'A5_ABUSOTHR','A5_ABUSX','A5_CBOTHR','A5_CBOTHRX','A5_CHRON_OTH','A5_CHRON_OTHX','A5_CVOTHR','A5_CVOTHRX','A5_DEP2YRS','A5_DEPOTHR','A5_NCOTHR','A5_NCOTHRX',
               'A5_PACKSPER','A5_PDOTHR','A5_PDOTHRYR','A5_PDYR','A5_PSYCDISX','A5_QUITSMOK','A5_SMOKYRS','A5_STROK1YR','A5_STROK2YR','A5_STROK3YR','A5_STROK4YR','A5_STROK5YR',
               'A5_STROK6YR','A5_TIA1YR','A5_TIA2YR','A5_TIA3YR','A5_TIA4YR','A5_TIA5YR','A5_TIA6YR','A5_TOBAC100','A5_TOBAC30','A5_TOBACLSTYR','A5_TRAUMEXT','APOE_GENOTYPE',
               'APOE_GENOTYPE_DIGITS','APOE_E2_COUNT','APOE_E3_COUNT','APOE_E4_COUNT','B1_HEARAID','B1_HEARING','B1_HEARWAID','B1_HEIGHT','B1_HRATE','B1_VISCORR','B1_VISION',
               'B1_VISWCORR','B1_WEIGHT','B5_NPIQINF','B5_NPIQINFX','B5_DELSEV','B5_HALLSEV','B5_AGITSEV','B5_DEPDSEV','B5_ANXSEV','B5_ELATSEV','B5_APASEV','B5_DISNSEV',
               'B5_IRRSEV','B5_MOTSEV','B5_NITESEV','B5_APPSEV','C1_ANIMAL','C1_BOSTON30','C1_BOSTON60','C1_DATEX','C1_CDRCA','C1_CDRGLOB','C1_CDRHOB','C1_CDRJU','C1_CDRMEM',
               'C1_CDROR','C1_CDRPER','C1_CDRSUM','C1_CERAD_LL_1','C1_CERAD_LL_2','C1_CERAD_LL_3','C1_CERAD_LL_DELAY','C1_CERAD_LL_TOT','C1_CERAD_WR_DISCRIM','C1_CERAD_WR_NO',
               'C1_CERAD_WR_YES','C1_CLOCK','C1_CLOX1','C1_CLOX2','C1_FAS_A','C1_FAS_F','C1_FAS_S','C1_GDS15','C1_GDS30','C1_LITPROB','C1_MMSE','C1_SS_AMNART','C1_SS_BOSTON60',
               'C1_SS_COMBINED_DIGTOT','C1_SS_COMBINED_LM_I','C1_SS_COMBINED_LM_II','C1_SS_COMBINED_VR_I','C1_SS_COMBINED_VR_II','C1_SS_COWAT','C1_SS_TRAILA','C1_SS_TRAILB',
               'C1_SS_WAIS3_DIGTOT','C1_SS_WAISR_DIGTOT','C1_SS_WMS3_LM_I','C1_SS_WMS3_LM_II','C1_SS_WMS3_VR_I','C1_SS_WMS3_VR_II','C1_SS_WMSR_DIGTOT','C1_SS_WMSR_LM_I','C1_SS_WMSR_LM_II',
               'C1_SS_WMSR_VR_I','C1_SS_WMSR_VR_II','C1_TAPS','C1_TCS_DK','C1_TCS_LS','C1_TCS_OTH','C1_TCS_PSV','C1_TOOIMPAIRED','C1_TRAILA','C1_TRAILAERR','C1_TRAILB',
               'C1_TRAILBERR','C1_WAIS3_DIGIB','C1_WAIS3_DIGIF','C1_WAIS3_DIGILB','C1_WAIS3_DIGILF','C1_WAIS3_DIGTOT','C1_WAISR_DIGIB','C1_WAISR_DIGIF','C1_WAISR_DIGILB',
               'C1_WAISR_DIGILF','C1_WAISR_DIGTOT','C1_WMS3_LMEM1','C1_WMS3_LMEM2','C1_WMS3_STORY1A','C1_WMS3_STORY1B1','C1_WMS3_STORY1B2','C1_WMS3_STORY2A','C1_WMS3_STORY2B','C1_WMS3_VR_A',
               'C1_WMS3_VR_B','C1_WMS3_VR_C','C1_WMS3_VR_D','C1_WMS3_VR_E','C1_WMS3_VR2_A','C1_WMS3_VR2_B','C1_WMS3_VR2_C','C1_WMS3_VR2_D','C1_WMS3_VR2_E','C1_WMS3_VRI','C1_WMS3_VRII',
               'C1_WMSR_DIGIB','C1_WMSR_DIGIF','C1_WMSR_DIGILB','C1_WMSR_DIGILF','C1_WMSR_DIGTOT','C1_WMSR_LMEM1','C1_WMSR_LMEM2','C1_WMSR_STORY1A','C1_WMSR_STORY1B1','C1_WMSR_STORY2A',
               'C1_WMSR_STORY2B','C1_WMSR_VR_A','C1_WMSR_VR_B','C1_WMSR_VR_C','C1_WMSR_VR_D','C1_WMSR_VR2_A','C1_WMSR_VR2_B','C1_WMSR_VR2_C','C1_WMSR_VR2_D','C1_WMSR_VRI','C1_WMSR_VRII',
               'D1_ALCDEM','D1_ALCDEMIF','D1_BRNINJIF','D1_COGOTH','D1_COGOTHIF','D1_COGOTHX','D1_CORTIF','D1_DEMENTED','D1_DEMUN','D1_DEMUNIF','D1_DEPIF','D1_DLB','D1_DLBIF','D1_DOWNS',
               'D1_DOWNSIF','D1_DYSILLIF','D1_FTD','D1_FTDIF','D1_HUNT','D1_HUNTIF','D1_HYCEPHIF','D1_IMPNOMCI','D1_MCIAMEM','D1_MCIAPATT','D1_MCIAPEX','D1_MCIAPLAN','D1_MCIAPLUS',
               'D1_MCIAPVIS','D1_MCIN1ATT','D1_MCIN1EX','D1_MCIN1LAN','D1_MCIN1VIS','D1_MCIN2ATT','D1_MCIN2EX','D1_MCIN2LAN','D1_MCIN2VIS','D1_MCINON1','D1_MCINON2','D1_MEDS','D1_MEDSIF',
               'D1_NEOPIF','D1_NORMCOG','D1_OTHPSY','D1_OTHPSYIF','D1_PARKIF','D1_POS_VASC','D1_POS_VASCIF','D1_POSSAD','D1_POSSADIF','D1_PPAOTHR','D1_PPAPHIF','D1_PRION',
               'D1_PRIONIF','D1_PROBAD','D1_PROBADIF','D1_PSP','D1_PSPIF','D1_SEMDEMAG','D1_SEMDEMAN','D1_STROKEIF','D1_VASCIF','D1_WHODIDDX','E1_RESIDE_DAT','P1_BDATEENROLLX',
               'P1_DNACOLLECTED','P1_DNATYPE','P1_INBIOMARKER','P1_INGENETICS','PROTEO_ADIPONECTIN','PROTEO_BFGF','PROTEO_CLUSTERIN','PROTEO_CRP','PROTEO_EOTAXIN_HUMAN',
               'PROTEO_EOTAXIN_3_HUMAN','PROTEO_FABP3','PROTEO_FACTOR_VII','PROTEO_FLT_1','PROTEO_GLUCAGON','PROTEO_GM_CSF_HUMAN','PROTEO_IFN_Y_HUMAN','PROTEO_IL_10_HUMAN','PROTEO_IL_12_P40_HUMAN',
               'PROTEO_IL_12_P70_HUMAN','PROTEO_IL_13_HUMAN','PROTEO_IL_15','PROTEO_IL_16','PROTEO_IL_17A','PROTEO_IL_1A','PROTEO_IL_1B_HUMAN','PROTEO_IL_2_HUMAN','PROTEO_IL_4_HUMAN','PROTEO_IL_5_HUMAN',
               'PROTEO_IL_6_HUMAN','PROTEO_IL_7_HUMAN','PROTEO_IL_8_HUMAN','PROTEO_IL_8_HA','PROTEO_INSULIN','PROTEO_IP_10_HUMAN','PROTEO_LBP','PROTEO_LEPTIN','PROTEO_MCP_1_HUMAN','PROTEO_MCP_4_HUMAN',
               'PROTEO_MDC_HUMAN','PROTEO_MIP_1A_HUMAN','PROTEO_MIP_1B_HUMAN','PROTEO_MPO','PROTEO_NT_PROBNP','PROTEO_PIGF','PROTEO_PYY','PROTEO_RESISTIN','PROTEO_SAA','PROTEO_SICAM_1',
               'PROTEO_SVCAM_1','PROTEO_TARC_HUMAN','PROTEO_TIE_2','PROTEO_TNF_A_HUMAN','PROTEO_TNF_B','PROTEO_TOTAL_GIP','PROTEO_VEGF_ANGIO_PLATE','PROTEO_VEGF_CYTO_PLATE','PROTEO_VEGF_C',
               'PROTEO_VEGF_D','X1_ANGINA_SR','X1_ARRHY_SR','X1_ATRIAL_SR','X1_BMIGT30','X1_CHF_SR','X1_HYPER_HAS','X1_HYPERLIP_HAS','X1_HYPERLIP_SR','X1_MI_SR','X1_OBESE_OTHX','X1_SMOKE_CUR',
               'X1_SMOKE_EVER','X2_IDURM','X2_IDURY','X2_MRDURM','X2_MRDURY','X2_PHYEST','X2_PHYESTFIRM','PID','GWAS','RBM_Rule_Based_Medicine','RBM_Rule_Based_Medicine_tp','RBM_Batch','RBM_TARC_PID',
               'RBM_ACE_CD143','RBM_Adiponectin','RBM_AgRP','RBM_Alpha_1','RBM_Alpha_2','RBM_Alpga_F','RBM_Amphiregulin','RBM_ANG_2','RBM_Angiotensinogen','RBM_APO_A1','RBM_APO_CIII',
               'RBM_APO_H','RBM_ASP','RBM_AXL','RBM_BLC','RBM_B2M','RBM_BTC','RBM_BMP6','RBM_BDNF','RBM_CRP','RBM_CA_125','RBM_CA_19_9','RBM_CEA','RBM_CD40','RBM_CD40L','RBM_CgA',
               'RBM_Complement_3','RBM_Cortisol','RBM_CK_MB','RBM_CTGF','RBM_EGF','RBM_EGF_R','RBM_ENA_78','RBM_EN_RAGE','RBM_Eotaxin','RBM_Eotaxin_3','RBM_Epiregulin','RBM_Factor_VII',
               'RBM_FAS','RBM_FASL','RBM_FABP','RBM_Ferritin','RBM_Fibrinogen','RBM_FSH','RBM_Galanin','RBM_G_CSF','RBM_Active_GLP_1','RBM_GSTs','RBM_GRO_alpha','RBM_GH','RBM_Haptoglobin',
               'RBM_HB_EGF','RBM_HCC_4','RBM_HGF','RBM_I_309','RBM_ICAM_1','RBM_IFNg','RBM_IgA','RBM_IgE','RBM_IGF_1','RBM_IGF_BP_2','RBM_IgM','RBM_IL_10','RBM_IL_12p40',
               'RBM_IL_13','RBM_IL_15','RBM_IL_16','RBM_IL_18','RBM_IL_1ra','RBM_IL_3','RBM_IL_5','RBM_IL_7','RBM_IL_8','RBM_Insulin','RBM_Leptin','RBM_LH','RBM_Lpa','RBM_MCP_1',
               'RBM_MDC','RBM_MIF','RBM_MIP_1a','RBM_MIP_1b','RBM_MMP_3','RBM_MPO','RBM_Myoglobin','RBM_OSM','RBM_PAI_1','RBM_PP','RBM_PDGF','RBM_Progesterone','RBM_Prolactin',
               'RBM_PAP','RBM_PARC','RBM_RANTES','RBM_Resistin','RBM_S100b','RBM_SAP','RBM_SGOT','RBM_SHBG','RBM_SOD','RBM_Sortilin','RBM_sRAGE','RBM_SCF','RBM_Tenascin_C','RBM_Testosterone',
               'RBM_TGF_alpha','RBM_THPO','RBM_THPO_1','RBM_TECK','RBM_TSH','RBM_TBG','RBM_TIMP_1','RBM_TF','RBM_TNF_RII','RBM_TNF_alpha','RBM_TNF_beta','RBM_TRAIL_R3','RBM_VCAM_1',
               'RBM_VDBP','RBM_VEGF','RBM_VWF','Q1_Quanterix','Q1_Quanterix_tp','Q1_YKL_40','Q1_GFAP','Q1_NFL','Q1_Total_tau','Q1_UCHL1','Q1_CD14','E1_DIED','E1_EXITDATEX','E1_LOST',
               'E1_RESIDE_CARE','E1_WDOTHREAS','E1_WDOTHREASX','E1_WITHDREW','F1_PSMS1','F1_PSMS2','F1_PSMS3','F1_PSMS4','F1_PSMS5','F1_PSMS6','F1_PSMSTOTSCR','F2_IADL1','F2_IADL2',
               'F2_IADL3','F2_IADL4','F2_IADL5','F2_IADL6','F2_IADL7','F2_IADL8','F2_IADLTOTSCR','I1_INBIRYR','I1_INCALLS','I1_INDATECONTX','I1_INEDUC','I1_INHISP','I1_INHISPOR',
               'I1_INHISPOX','I1_INHOWCONTACT','I1_INLIVWTH','I1_INRACE','I1_INRACEX','I1_INRASEC','I1_INRASECX','I1_INRATER','I1_INRATERX','I1_INRELTO','I1_INRELTOX',
               'I1_INRELY','I1_INSEX','I1_INVISITS','I1_ISNEWINFORM','P1_BGRESULT','P1_BIOSERUM','P1_BUFFY','P1_CSF','P1_DATEDRAWX','P1_DATEFOODX','P1_DATESTICKX','P1_GDATEENROLLX',
               'P1_HRSAFTFOOT','P1_PLASMA','P1_PT_TYPE_OTHX','P1_PTTYPEDESC','P1_SERUM','P1_SHARE_AGREE','P1_SHARE_DATEX','P1_TIMEDRAWX','P1_TIMEFOODX','P1_TIMESTICKX','P1_WHOLEBLOOD',
               'P1_WHYNOTALL','P1_WHYNOTALLX', 'D1_PNAPH','A5_SEIZURES'], axis=1)
    #Replace empty strings with null values
  df = df.replace(r'^\s*$', np.nan, regex=True)
  nullvals=list(df.isna().sum()[df.isna().sum()>0].index)
  df[nullvals]=df[nullvals].fillna(9)
    #convert categorical object columns to floats
  categoricalcols=list(df.dtypes[df.dtypes==object].index)
  df[categoricalcols]=df[categoricalcols].astype(float)
  
  return(data)


